### ISSUE TITLE
Server core-dumps after ~16 minutes of operation

### ISSUE THREAD

**Issue by platisd** [platisd/indoor-navigation-system#68] opened 2017-12-05 00:25 UTC
## Description
The `ins_server` core-dumps after approximately 16 minutes of operation, regardless of whether it is handling incoming data or not. The defect was reproducible 100% of the times.

### Ways to reproduce
Have `ins_server` executing for long amounts of time.

### Related logs
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  No route to host
> Aborted (core dumped)

## Definition of Done
The `ins_server` can run for indefinite amounts of time.

**Comment by samup4web** [comment] 2017-12-05 17:52
@platisd hmm, what is your setup like? 
I tried running the ins_server on my machine and it runs for over 1 hour, and also accepted request thereafter. See the time-stamp prints in the screenshot below. 
![screenshot](https://user-images.githubusercontent.com/1077252/33621816-4f62d8a2-d9ec-11e7-9b7e-86821e3c3360.png)

I will investigate further...

**Comment by samup4web** [comment] 2017-12-05 17:53
I still have the server running, I will see how long before I reproduce the problem.

**Comment by platisd** [comment] 2017-12-05 18:32
How did it go? Weird... otherwise it must be some local weird error, since I could consistently reproduce it.

**Comment by samup4web** [comment] 2017-12-05 18:38
Still running at 19:38 ...

**Comment by platisd** [comment] 2017-12-05 18:48
Weird... Let's close this for now and I will open it again if I have a different angle on it.

**Comment by samup4web** [comment] 2017-12-05 18:50
@lexious89 can you try to run the server on your box and let's see if you can reproduce the problem.

**Comment by samup4web** [comment] 2017-12-09 16:55
I manage to reproduce this issue. I will be investigating further...

**Comment by platisd** [comment] 2017-12-09 17:27
Interesting, keep us posted! :+1:

**Comment by samup4web** [comment] 2017-12-09 17:30
Strangely enough, I am on my second attempt to reproduce the problem after the first crash with no success. Will be testing on both my ubuntu box and rasberrypi.

**Comment by samup4web** [comment] 2017-12-09 17:34
On a side note, @platisd are you on slack?

**Comment by platisd** [comment] 2017-12-09 17:40
I sure am! 😛 

Send invite to my work mail if you're making a channel

**Comment by samup4web** [comment] 2017-12-09 17:50
Done.

**Comment by samup4web** [comment] 2017-12-09 18:35
OK, couldn't get it to crash. So, am making a new run on rasberrypi now. 
* ins service start time - `[2017-12-09 17:36:55.200]` 
* ins_node start time - `[2017-12-09 18:16:52.178]`
* current time - `[2017-12-09 18:35:01.948]` 

This will be running all night, so, fingers crossed.

**Comment by platisd** [comment] 2017-12-09 19:08
What is your setup like? Are you using the wifi_module.ino without letting it sleep?

**Comment by samup4web** [comment] 2017-12-09 19:10
Yes, modified wifi_module to not sleep and send data continuously with `delay(20000);`. I am using NodeMCU device for this. 
For the server, I am running on a fresh installation of rasberrypi.

**Comment by samup4web** [comment] 2017-12-10 14:05
Strange that INS service has been running all night/day and still running (on rasberrypi) 
* current time - `[2017-12-10 14:01:14.282]`

I had to press reset button on ins_node this morning because it wasn't sending out data. I guess due to network connection.

**Comment by platisd** [comment] 2017-12-10 14:07
I will also try to debug this when I find the time. Any suggestions on where to add extra logs?

**Comment by samup4web** [comment] 2017-12-10 14:10
Okay, great! As for extra logs, none that I can think of now.

**Comment by samup4web** [comment] 2018-01-20 15:35
Closing this issue since we haven't observed this issue lately. This can be re-opened again if problem reoccur

**Closed as completed by samup4web** 2018-01-20 15:35 UTC
Labels: bug, [epic] server

**Comment by platisd** [comment] 2018-01-20 15:37
I agree. That being said, I think it could make sense to invest in making a Docker image to make sure everyone is running things in the same environment. :+1:

**Comment by samup4web** [comment] 2018-01-20 15:39
Haha, nice idea. Taking it to another level :smile_cat:
